### ISSUE TITLE
Feature #1: User Can Create New Tasks

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/todo-list#1]
## Feature
User can create new tasks

## Functionality
User can create a new task to add to the todo list.

## Wireframes
![image](https://github.com/Malcolm-Abbott/todo-list/assets/136769102/7d22ae17-363e-4e8a-ae25-ddd90a7e963b)

## Task Lists
- [ ] Install react-router-dom dependencies and add the BrowserRouter Component to main.tsx
- [ ] Create routes to contain all of the project's components
- [ ] Create a header component including the Outlet component
- [ ] Create a  component for the todo list
- [ ] Store data through state and localStorage
